### ISSUE TITLE
Player labels sometime appear as undefined

### ISSUE THREAD

**Issue by zedahmad** [ahmadzed/ghouls-race-server#12]
Caused by a race condition: after a player connects to the server, the client script must send the first data chunk before an active ghost viewer updates the player list and creates the ghost objects

**Comment by zedahmad** [comment]
Corrected in 96b2bb62a55b8936eb9c19fba88984ecaaf6fa5c

**Comment by ChangXiaoning** [comment]
Hi @ahmadzed 
I am a Node.js learner and interested in this issue. My understanding is that the ghost viewer updates the player list at code 'let players = new Map(data);' and creates the ghost objects at'if (!ghosts.has(key))' the if-branch. However, I am puzzled with how the race condition happens. Specifically, why can the race condition make the player label undefined if client script sends the first data chunk after the active ghost viewer updates the player list and creates the ghost objects. Look forwards for you replay. Thx :)
